version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: rapid_vax
      MYSQL_USER: user
      MYSQL_PASSWORD: 5G45S63AMG
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
