import { Inter } from 'next/font/google'
import Head from 'next/head'; 
import './globals.css';
import logo from '../assets/logo.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <header>
          <div className="logo">
            <img src={logo} alt="My App Logo" />
          </div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
